Fixed Webdrivers::VersionError with chrome version greater than 115
titusfortner/webdrivers pull request #249
Opened 2023-07-27 09:48 UTC by sadahiro-ono

similar Issue: https://github.com/titusfortner/webdrivers/issues/247

f the version is 115 or higher, the API can be used, so if the version is 115 or higher, the stable version is obtained and downloaded from the API.

refarence
- https://chromedriver.chromium.org/downloads
- https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints

2023-07-27 17:55 UTC, titusfortner commented
Thanks for the PR. It looks like it isn't backwards compatible. Can you look at why the tests are failing?

2023-07-28 10:12 UTC, sadahiro-ono commented
@titusfortner 
Local tests passed, but I made some fixes to lower the impact, could you please run a CI?

2023-07-28 13:34 UTC, sadahiro-ono commented
@titusfortner 
The main branch is also not passing the tests. I sorry, Could you please confirm this for me?
https://github.com/titusfortner/webdrivers/actions/runs/5683791993/job/15405104246

2023-07-28 15:11 UTC, alexshenia commented
` expected StandardError with message matching /Net::HTTPServerException: 404 "Not Found"/, got #<Webdrivers::NetworkError: Net::HTTPClientException: 404 "Not Found" with https://github.com/mozilla/geckodriver/releases/download/v0.2.0/geckodriver-v0.2.0-linux64.tar.gz>`

is it not make any sense cause geckodriver starts from 0.8.0

2023-07-28 15:17 UTC, alexshenia commented
` Webdrivers::NetworkError:
       Net::HTTPClientException: 404 "Not Found" with https://msedgedriver.azureedge.net/114.0.1823.90/edgedriver_mac64.zip`
https://msedgedriver.azureedge.net/ does not have this build  `114.0.1823.90/edgedriver_mac64.zip`

2023-07-28 15:42 UTC, titusfortner commented
StandardError is the superclass, it is the value of the String it failed on. Not sure if it is happenstance or common that MS doesn't do releases for all platforms for all patch versions, but not good either way.

2023-07-28 21:24 UTC, titusfortner requested changes
1. Thanks for putting this together and adding tests
2. I really hate looking at old code I've written. 
3. We probably need to exclude `chromedriver.rb` from `Metrics/ClassLength` in `.rubocop.yml`.

2023-07-28 21:24 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +        url = if version >= normalize_version('115')
We can use https://chromedriver.chromium.org/downloads/version-selection for the error message

2023-07-28 21:24 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +          driver_version >= normalize_version('106.0.5249.61') ? 'mac-arm64' : 'mac64-m1'
if we put this conditional in `#apple_filename` we don't need to add `#apple_filename_api`.

2023-07-28 21:24 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +      def chrome_for_testing_base_url
Not sure if it matters, but this breaks https://github.com/titusfortner/webdrivers/wiki/Using-with-VCR-or-WebMock

2023-07-28 21:25 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +          driver_version >= normalize_version('106.0.5249.61') ? 'mac-arm64' : 'mac64-m1'
hmm, I deleted the wrong comment looks like. Let me fix.

2023-07-28 21:26 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +          if driver_version >= normalize_version('115')
If we move this conditional to `#apple_filename` we don't need to add `#apple_filename_api`.

2023-07-28 21:27 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +          driver_version >= normalize_version('106.0.5249.61') ? 'mac-arm64' : 'mac64-m1'
moved the comment to where it was supposed to go below.

2023-07-31 00:15 UTC, yykamei commented on spec/webdrivers/chromedriver_spec.rb
> +        msg = %r{Can not reach https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json}
How about considering the both cases for v115+ and v114 or earlier? The Gem is expected to print "Can not reach ...", and the target URL is not important here.

```suggestion
        msg = %r{Can not reach (?:https://googlechromelabs.github.io|https://chromedriver.stor
age.googleapis.com)}
```

2023-07-31 00:15 UTC, yykamei commented on spec/webdrivers/chromedriver_spec.rb
> +        msg = %r{Can not reach https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json}
```suggestion
        msg = %r{Can not reach (?:https://googlechromelabs.github.io|https://chromedriver.stor
age.googleapis.com)}
```

2023-07-31 00:19 UTC, yykamei commented on spec/webdrivers/chromedriver_spec.rb
> +      msg = %r{^Can not reach https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json}
```suggestion
      msg = %r{Can not reach (?:https://googlechromelabs.github.io|https://chromedriver.stor
age.googleapis.com)}
```

2023-07-31 00:47 UTC, sadahiro-ono commented on lib/webdrivers/chromedriver.rb
> +      def chrome_for_testing_base_url
Do we need to support a version that we cannot get from[ this endpoint](https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json)?
I believe we can change the base_url to the API endpoint if we don't need it.

2023-07-31 17:36 UTC, titusfortner commented on lib/webdrivers/chromedriver.rb
> +      def chrome_for_testing_base_url
yes, we still need to support the older versions

2023-07-31 19:33 UTC, titusfortner commented
Merged here — https://github.com/titusfortner/webdrivers/commit/97fb1e2b842c427a885553ac695ecdbf303344ba

Thank you!

2023-07-31 19:33 UTC, closed without merging